version: '2.1'

services:

  postgres:
    image: postgres:10.3
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - freemaill
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  freemaill:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - freemaill
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:root@postgres/postgres"
networks:
  freemaill:
    driver: bridge
volumes:
  data:
